apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2021-05-15T07:29:58Z"
  generation: 1
  labels:
    app: sri
  name: sri
  namespace: default
  resourceVersion: "4873"
  uid: e975778b-329d-4cea-80b2-1ff4e9a26f0b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sri
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sri
    spec:
      containers:
      - image: srikargopu/sri_repo:latest
        imagePullPolicy: IfNotPresent
        name: sri-repo-6x8tb
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
