apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2021-05-15T08:14:22Z"
  generation: 1
  labels:
    app: sri
  name: sri
  namespace: default
  resourceVersion: "8429"
  uid: 9b2d01f9-1bea-494e-afab-58493bdd2c71
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sri
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sri
    spec:
      containers:
      - image: srikargopu/sri_repo:latest
        imagePullPolicy: Always
        name: sri-repo-8rhll
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
